### ISSUE TITLE
start domain to company map

### ISSUE THREAD

**Issue by trozamon** [trozamon/si301project#2]
I am planning on adding a JSON file in the data folder to map domain names from emails to company names

**Comment by trozamon** [comment]
I added `src/si301/mailmap.py` - just add more company names. I also added some email-related tests that are failing, so some code needs to be fixed.

**Comment by trozamon** [comment]
Could you take out the personal domains or put them in a different dictionary? Also, could you alphabetize it to make it easier to read?

**Comment by prenner** [comment]
Yeah, I can do that. So just major companies in that dictionary?

On Tue, Mar 29, 2016 at 12:25 PM, Alec Ten Harmsel <notifications@github.com

> wrote:
> 
> Could you take out the personal domains or put them in a different
> dictionary? Also, could you alphabetize it to make it easier to read?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/trozamon/si301project/issues/2#issuecomment-202984816

## 

Patrick W. Renner

**Comment by prenner** [comment]
(or universities..just not personal sites? or what?)

On Tue, Mar 29, 2016 at 3:17 PM, Patrick W. Renner patwrenner@gmail.com
wrote:

> Yeah, I can do that. So just major companies in that dictionary?
> 
> On Tue, Mar 29, 2016 at 12:25 PM, Alec Ten Harmsel <
> notifications@github.com> wrote:
> 
> > Could you take out the personal domains or put them in a different
> > dictionary? Also, could you alphabetize it to make it easier to read?
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/trozamon/si301project/issues/2#issuecomment-202984816
> 
> ## 
> 
> Patrick W. Renner

## 

Patrick W. Renner

**Comment by trozamon** [comment]
A better term would be "organizations". Yes, I thing we should include companies, universities, and other organizations like the FSF, GNU, Debian, Fedora, etc.

**Comment by trozamon** [comment]
Looks good. We can add more in the future as needed
